EMAIL_SENDER = "leonardasrdelic@windowslive.com"
EMAIL_RECIPIENT = "leonardasrdelic@windowslive.com"
SMTP_SERVER = "smtp.office365.com"
SMTP_PORT = 587
SMTP_USERNAME = "leonardasrdelic@windowslive.com"
SMTP_PASSWORD = "uttuegjyrweouhtj"
